name: dw.biggs
favicon: null
layout_spectrum: 0.52743
typography_spectrum: 0.24062533769756556
title: DW.Biggs Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0e5ff'
    - '#9c0202'
    - '#024380'
    - '#0399ef'
    - '#eac202'
  brandStrength: 0.625
  lightness: 0.189593190792948
  saturation: 0.508662509964779
  rhythmicContrast: 0.07632768643088639
purpose: []
